services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: restaurent_saas
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - redis-data:/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '4000:4000'

  realtime:
    build:
      context: .
      dockerfile: apps/realtime/Dockerfile
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '4001:4001'

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - .env
    depends_on:
      api:
        condition: service_started
    ports:
      - '3000:3000'

  waiter:
    build:
      context: .
      dockerfile: apps/waiter/Dockerfile
    env_file:
      - .env
    depends_on:
      api:
        condition: service_started
    ports:
      - '4173:4173'

  kitchen:
    build:
      context: .
      dockerfile: apps/kitchen/Dockerfile
    env_file:
      - .env
    depends_on:
      api:
        condition: service_started
    ports:
      - '4174:4174'

volumes:
  mongo-data:
  redis-data:

