/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#f9f9ff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#ecf1ff',
        'inverse-primary': '#ffb77d',
        'inverse-surface': '#263143',
        'on-background': '#111c2d',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#2f1500',
        'on-primary-fixed-variant': '#6e3900',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#57657a',
        'on-secondary-fixed': '#0d1c2e',
        'on-secondary-fixed-variant': '#3a485b',
        'on-surface': '#111c2d',
        'on-surface-variant': '#554336',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        outline: '#887364',
        'outline-variant': '#dbc2b0',
        primary: '#8d4b00',
        'primary-container': '#b15f00',
        'primary-fixed': '#ffdcc3',
        'primary-fixed-dim': '#ffb77d',
        secondary: '#515f74',
        'secondary-container': '#d5e3fc',
        'secondary-fixed': '#d5e3fc',
        'secondary-fixed-dim': '#b9c7df',
        surface: '#f9f9ff',
        'surface-bright': '#f9f9ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'surface-container-low': '#f0f3ff',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#cfdaf2',
        'surface-tint': '#904d00',
        'surface-variant': '#d8e3fb',
        tertiary: '#825100',
        'tertiary-container': '#a36700',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        full: '9999px',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        base: '8px',
        gutter: '16px',
        lg: '24px',
        margin: '24px',
        md: '16px',
        sm: '8px',
        xl: '40px',
        xs: '4px',
      },
      fontFamily: {
        'body-lg': ['Work Sans', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'data-tabular': ['Work Sans', 'sans-serif'],
        'headline-lg': ['Work Sans', 'sans-serif'],
        'headline-md': ['Work Sans', 'sans-serif'],
        'headline-xl': ['Work Sans', 'sans-serif'],
        'label-md': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { fontWeight: '400', lineHeight: '24px' }],
        'body-md': ['14px', { fontWeight: '400', lineHeight: '20px' }],
        'data-tabular': ['14px', { fontWeight: '500', lineHeight: '20px' }],
        'headline-lg': ['28px', { fontWeight: '600', letterSpacing: '-0.01em', lineHeight: '36px' }],
        'headline-md': ['20px', { fontWeight: '600', lineHeight: '28px' }],
        'headline-xl': ['36px', { fontWeight: '700', letterSpacing: '-0.02em', lineHeight: '44px' }],
        'label-md': ['12px', { fontWeight: '600', letterSpacing: '0.05em', lineHeight: '16px' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
